name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'papers/**'
      - 'rfcs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'papers/**'
      - 'rfcs/**'
      - '*.md'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [Win32, x64]
    steps:
    - uses: actions/checkout@v1
    - name: cmake configure
      run: cmake . -A ${{matrix.arch}} -DLUAU_WERROR=ON -DLUAU_NATIVE=ON
    - name: cmake build
      run: cmake --build . --target Luau.UnitTest Luau.Conformance --config Debug
    - name: run tests
      shell: bash # necessary for fail-fast
      run: |
        Debug/Luau.UnitTest.exe
        Debug/Luau.Conformance.exe
        Debug/Luau.UnitTest.exe --fflags=true
        Debug/Luau.Conformance.exe --fflags=true
    - name: run extra conformance tests
      shell: bash # necessary for fail-fast
      run: |
        Debug/Luau.Conformance.exe -O2
        Debug/Luau.Conformance.exe -O2 --fflags=true
        Debug/Luau.Conformance.exe --codegen
        Debug/Luau.Conformance.exe --codegen --fflags=true
        Debug/Luau.Conformance.exe --codegen -O2
        Debug/Luau.Conformance.exe --codegen -O2 --fflags=true
    - name: cmake cli
      shell: bash # necessary for fail-fast
      run: |
        cmake --build . --target Luau.Repl.CLI Luau.Analyze.CLI Luau.Compile.CLI --config Debug # match config with tests to improve build time
        Debug/luau tests/conformance/assert.lua
        Debug/luau-analyze tests/conformance/assert.lua
        Debug/luau-compile tests/conformance/assert.lua
